version: '3.7'

services:
  mongo1:
    image: mongo:5.0
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]
  mongo2:
    image: mongo:5.0
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27018:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]
  mongo3:
    image: mongo:5.0
    hostname: mongo3
    container_name: mongo3
    ports:
      - 27019:27017
    entrypoint: ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]
    
  mongosetup:
    image: mongo:5.0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

  user_service:
    container_name: user_service
    build:
      context: ./user_service
    ports:
      - 8080:8080
    environment:
        USER_SERVICE_PORT: 8080
        ACCOUNT_SERVICE_URL: 'http://account_service:8087'
        MSG_SERVICE_URL: 'http://message_service:8088'
        POST_SERVICE_URL: 'http://post_service:8089'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sn-network
      
  account_service:
    container_name: account_service
    build:
      context: ./account_service
    environment:
        ACCOUNT_SERVICE_PORT: 8087
    expose:
      - "8087"
    depends_on:
      user_service:
        condition: service_started
    networks:
      - sn-network
      
  message_service:
    container_name: message_service
    build:
      context: ./message_service
    environment:
        MSG_SERVICE_PORT: 8088
    expose:
      - "8088"
    depends_on:
      user_service:
        condition: service_started
    networks:
      - sn-network
      
  post_service:
    container_name: post_service
    build:
      context: ./post_service
    environment:
        POST_SERVICE_PORT: 8089
    depends_on:
      user_service:
        condition: service_started
    expose:
      - "8089"
    networks:
      - sn-network
      

networks:
  sn-network:
    driver: "bridge"

volumes:
  mongodata: